### ISSUE TITLE
should support multipart/form-data post requests

### ISSUE THREAD

**Issue by pbearne** [rmccue/Requests#565] opened 2021-09-24 22:00 UTC
Currently, we need to be a bit creative to attach files to a post request 
```php
		// Create a boundary. We'll need it as we build the payload.
		$boundary = md5( time() . $ext );

		// End of Line
		$eol = "\r\n";

		// Construct the payload in multipart/form-data format
		$payload  = '';
		$payload .= '--' . $boundary;
		$payload .= $eol;
		$payload .= 'Content-Disposition: form-data; name="submitted_file"; filename="' . $name . '"' . $eol;
		$payload .= 'Content-Type: ' . $format . $eol;
		$payload .= 'Content-Transfer-Encoding: binary' . $eol;
		$payload .= $eol;
		$payload .= $contents;
		$payload .= $eol;
		$payload .= '--' . $boundary . '--';
		$payload .= $eol . $eol;

		// Create args for wp_remote_request
		$args = array(
			'headers' => array(
				'accept'       => 'application/json',
				'content-type' => 'multipart/form-data;boundary=' . $boundary,
			),
		);

		// Call the standard request function and return it.
		return $this->request( $api_method, $params, $http_method, $payload, $args );
```

I would like to be able to pass an array of mixed objects and have it be handled as multipart form if it is a POST/PUT/OPTIONS/PATCH call   

## Describe alternatives you've considered
code like above

## Additional context (optional)

- [X ] I am happy to help create a pull request to implement this feature myself.

**Comment by jrfnl** [comment] 2021-09-24 23:28
Duplicate of #289 with possible solution via PR #313 ?

**Comment by pbearne** [comment] 2021-09-27 18:44
yes #313 will work let's close this and get that merged

**Comment by jrfnl** [comment] 2021-09-27 23:19
Closing as duplicate of #289

**Closed as completed by jrfnl** 2021-09-27 23:19 UTC
Labels: Status: duplicate
